export { Home } from './Home/Home';
export { About } from './About/About';
export { Services } from './Services/Services';
export { Blog } from './Blog/Blog';
export { GetInTouch } from './GetInTouch/GetInTouch';
export { ServicesItems } from './Services/ServiceBlocks/ServicesItems';
export { ServicePage } from './Services/ServiceBlocks/ServicePage';
export { BlogPage } from './Blog/BlogPage';
export { ErrorPage } from './ErrorPage/ErrorPage';
